# Generated by Django 6.1 on 2026-08-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Direct URL to car image', max_length=500),
        ),
    ]
