from django.urls import path

from rides.views import (
    DriverAcceptRideAPIView,
    DriverArrivedAPIView,
    DriverArrivingAPIView,
    DriverCompleteRideAPIView,
    DriverEligibleRidesAPIView,
    DriverStartRideAPIView,
)
from .views import (
    CustomerProfileAPIView,
    CustomerRegisterAPIView,
    DriverProfileAPIView,
    DriverVehicleDetailAPIView,
    DriverVehicleListCreateAPIView,
    VehicleCategoryListAPIView,
)

urlpatterns = [
    path(
        "auth/register/",
        CustomerRegisterAPIView.as_view(),
        name="customer-register",
    ),
    path(
        "categories/",
        VehicleCategoryListAPIView.as_view(),
        name="vehicle-categories",
    ),
    path(
        "customers/me/",
        CustomerProfileAPIView.as_view(),
        name="customer-profile-me",
    ),
    path(
        "drivers/me/",
        DriverProfileAPIView.as_view(),
        name="driver-profile-me",
    ),
    path(
        "drivers/vehicles/",
        DriverVehicleListCreateAPIView.as_view(),
        name="driver-vehicles",
    ),
    path(
        "drivers/vehicles/<int:pk>/",
        DriverVehicleDetailAPIView.as_view(),
        name="driver-vehicle-detail",
    ),
    path(
        "drivers/rides/eligible/",
        DriverEligibleRidesAPIView.as_view(),
        name="driver-rides-eligible",
    ),
    path(
        "drivers/rides/<int:pk>/accept/",
        DriverAcceptRideAPIView.as_view(),
        name="driver-ride-accept",
    ),
    path(
        "drivers/rides/<int:pk>/arriving/",
        DriverArrivingAPIView.as_view(),
        name="driver-ride-arriving",
    ),
    path(
        "drivers/rides/<int:pk>/arrived/",
        DriverArrivedAPIView.as_view(),
        name="driver-ride-arrived",
    ),
    path(
        "drivers/rides/<int:pk>/start/",
        DriverStartRideAPIView.as_view(),
        name="driver-ride-start",
    ),
    path(
        "drivers/rides/<int:pk>/complete/",
        DriverCompleteRideAPIView.as_view(),
        name="driver-ride-complete",
    ),
]
