# Generated by Django 6.1 on 2026-08-25 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_vehiclecategory_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=500)),
                ('pickup_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('pickup_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_address', models.CharField(max_length=500)),
                ('destination_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_duration_minutes', models.PositiveIntegerField()),
                ('estimated_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('otp_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SEARCHING', 'Searching'), ('ACCEPTED', 'Accepted'), ('DRIVER_ARRIVING', 'Driver Arriving'), ('DRIVER_ARRIVED', 'Driver Arrived'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=30)),
                ('cancelled_by', models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('DRIVER', 'Driver'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=20, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.vehiclecategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.customerprofile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.driverprofile')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.vehicle')),
            ],
        ),
    ]
