# Generated by Django 6.1 on 2026-08-28 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('CUSTOMER_TO_DRIVER', 'Customer to Driver'), ('DRIVER_TO_CUSTOMER', 'Driver to Customer')], max_length=25)),
                ('rating', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rides.booking')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('booking', 'rating_type'), name='unique_booking_rating_per_direction')],
            },
        ),
    ]
